version: '3.8'

services:
  server:
    image: node:18-alpine
    container_name: mind-pwa-server
    restart: unless-stopped
    working_dir: /usr/src/app/server
    volumes:
      - /volume1/projects/mind-pwa:/usr/src/app
    # Use an env_file to load all variables from the .env at the project root
    env_file:
      - .env
    command: >
      sh -c "npm run start"

  nginx:
    image: nginx:latest
    container_name: mind-pwa-nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Use a test port
    volumes:
      - /volume1/web/mind-pwa-deploy:/usr/share/nginx/html
      - /volume1/projects/mind-pwa/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server