version: '3.8'

services:
  nginx-client-only:
    image: nginx:latest
    container_name: mind-pwa-nginx-client-only
    restart: unless-stopped
    ports:
      - "8080:80" # Use a test port to avoid conflicts
    volumes:
      # Points to the DEPLOYED PWA code
      - /volume1/web/mind-pwa-deploy:/usr/share/nginx/html
      # Points to a SIMPLIFIED Nginx config
      - /volume1/projects/mind-pwa/nginx/nginx.client-only.conf:/etc/nginx/conf.d/default.conf
